# Site settings
title: 元智网址大全
email: info@microwise-system.com
description: > # this means to ignore newlines until "baseurl:"
  这里列出了元智系统目前在线系统网址。
baseurl: "/hao123/" # the subpath of your site, e.g. /blog/
url: "http://microwise-system.github.io/hao123/" # the base hostname & protocol for your site
wechat_username: microwise_Coltd
weibo_username: 西安元智

# Build settings
markdown: kramdown
